# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: info@coursekata.org
author_name: CourseKata
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupytereverywhere
mimetype: ''
mimetype_name: ''
project_short_description: CourseKata Playground — a JupyterLite extension for K-12 education
python_name: jupytereverywhere
repository: https://github.com/coursekata/playground
test: true
viewer_name: ''
